- name: Deploy and Configure k8s for bootcamp
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    kubernetes_network: 10.142.0.0/24
    kubernetes_version: 1.25.5
    user: "{{ lookup('env','USER') }}"
    node_name: k8s
    calico_url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
    service_account: bootcamp
    namespace: default
  tasks:
    - name: Include k8s role
      ansible.builtin.include_role:
        name: k8s