- name: Deploy/Undeploy wiremock
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    app_name: wiremock
    app_image: vmartinvega/wiremock-training:latest
    app_port: 32100
    namespace: default
    replicas: 1
  tasks:
    - name: Set fact for token
      set_fact:
        token: "{{ lookup('env','K8S_CREDS_PSW') }}"

    - name: Debug token
      debug:
        var: token

    - name: Read state
      set_fact:
        state: "{{lookup('ansible.builtin.file', 'state/state.json') | from_json }}"

    - name: Include Wiremock role
      ansible.builtin.include_role:
        name: wiremock
