FROM ansible/ansible

LABEL maintainer="Vicente Martin Vega"

COPY --chown=0:0 requirements.txt .

RUN python3 -m pip install -r "requirements.txt"  && \
    mkdir /.cache && \
    chgrp -R 0 /.cache && \
    chmod -R g=u /.cache

RUN ansible-galaxy collection install kubernetes.core