- name: Deploy Wiremock 
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include training role
      ansible.builtin.include_role:
        name: training
      vars:
        app_name: wiremock
        app_image: 
        app_port: 32100

