- name: Deploy/Undeploy wiremock
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    service_account: bootcamp
    namespace: default
  tasks:
    # - name: Read state
    #   set_fact:
    #     state: "{{lookup('ansible.builtin.file', 'state/state.json') | from_json }}"
    # - ansible.builtin.debug:
    #     msg: "{{ state.port }}"
    # - name: Create Service Account
    #   shell: >-
    #     kubectl -n {{ namespace }} create serviceaccount {{ service_account }}

    # - name: Create Cluster Role
    #   shell: >-
    #     kubectl create clusterrolebinding clusterrolebinding-bootcamp --clusterrole=cluster-admin --serviceaccount={{ namespace }}:{{ service_account }}

    - name: Get Token 
      shell: >-
        kubectl get secret secret-bootcamp -o jsonpath='{.data.token}' | base64 --decode
      register: token

    - debug:
        var: token.stdout

    - name: Remove an existing Service object
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: testing
        name: web