- name: Set user folder
  set_fact:
    user_folder: "/home/{{ setup_jenkins__local_user_name }}"

- name: Get bytes for kubeconfig
  shell: "cat {{ user_folder }}/.kube/config | base64 --wrap=0"
  register: kubeconfig
  delegate_to: localhost

- name: Get bytes for kubeconfig
  set_fact:
    kubeconfig_file_bytes: "{{ kubeconfig.stdout }}" 

- name: Create Jenkins config
  set_fact: 
    config_content: "{{ lookup('ansible.builtin.template', 'casc-jenkins.yml.j2') | from_yaml }}"

- name: Create temporary folder for Jenkins config
  ansible.builtin.tempfile:
    state: directory
    suffix: temp
  register: temp_folder
  delegate_to: localhost

- name: Save jenkins config
  copy:
    dest: "{{ temp_folder.path }}/jenkins-conf.yaml"
    content: "{{ config_content }}"
  delegate_to: localhost

- name: Create jenkins config map
  ansible.builtin.shell: >-
    kubectl create configmap jenkins-conf --from-file={{ temp_folder.path }}/jenkins-conf.yaml
  delegate_to: localhost

- name: Deploy Jenkins resources
  ansible.builtin.include_tasks: _deploy_resource.yml
  loop:
    - pvc-jenkins.yml.j2
    - config-git-jenkins.yml.j2
    - deployment-jenkins.yml.j2
    - service-jenkins.yml.j2
    - service-jenkins-webservice.yml.j2
    - service-jenkins-tcp-port.yml.j2
    - service-jenkins-jnlp-port.yml.j2
    - secrets-jenkins.yml.j2
