apiVersion: v1
kind: Pod
spec:
  containers:
    - name: terraform
      image: docker.io/vmartinvega/bootcamp-terraform:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: IfNotPresent
